### ISSUE TITLE
Refresh issues in Connect Wallet page

### ISSUE THREAD

**Issue by mandoopapa** [tokamak-network/tokamak-rollup-hub#13]
### To Reproduce

※ Note: This is an issue on the PC version and has not been verified on Tablet or Mobile.

![image](https://github.com/user-attachments/assets/e5004a46-689d-4691-954f-606fb516fe04)

Clicking on the Metamask connection point does not respond. This may be an issue with my PC, so I'll need to recheck in multiple environments. Let me know if this works for you.

The problem is that when I refresh (F5) through Connect Wallet with the above window open, I get the screen below.

![image](https://github.com/user-attachments/assets/eca2acc6-4eba-41c3-b5a6-5b1a2c62e86d)

Additionally, the Learn more about wallet link looks like it should be directing to a document such as Metamask Docs.

### Current vs. Expected behavior

When I refresh from the Connect wallet page, it would be nice to be taken to that page or even home, just an opinion. 

### What browsers are you seeing the problem on?

Chrome

**Comment by ohbyeongmin** [comment]
Thank you so much! i forgot this.

**Comment by mandoopapa** [comment]
The footer changes on the Connect wallet page. 

![스크린샷 2024-09-24 094450](https://github.com/user-attachments/assets/90ad239f-6059-4c28-86c8-e545f7b20024)

![스크린샷 2024-09-24 094456](https://github.com/user-attachments/assets/5772f627-8dcd-4c52-93a5-010b12f0828a)

**Comment by ohbyeongmin** [comment]
#14
