### ISSUE TITLE
Arbitrary changes to the json file to be downloaded via input in the browser's URL address bar

### ISSUE THREAD

**Issue by mandoopapa** [tokamak-network/tokamak-rollup-hub#8]
### To Reproduce

Probably just an issue because it's currently in Test

![image](https://github.com/user-attachments/assets/7fe16098-69f5-47ac-9a01-c1aad5ee8441)

You can arbitrarily change what is written in the URL address field above and download the json file as you have changed it. 

In this way, you can change other values other than the inputs that the user can enter in the Devnet selection and download them as well.

![image](https://github.com/user-attachments/assets/5179c231-eb4d-4d7e-831f-358f5ee4c56b)

Originally, the contents of the red square, which cannot be entered, could also be arbitrarily changed.

### Current vs. Expected behavior

![image](https://github.com/user-attachments/assets/328b6942-ddcf-403b-bece-f6c35267f74a)

![image](https://github.com/user-attachments/assets/b5349908-6410-4cdc-81cc-76daff90b9eb)

For other services, the address bar doesn't reveal the contents.

### What browsers are you seeing the problem on?

Chrome

**Comment by ohbyeongmin** [comment]
This is not a bug. but i agree with you overall.

**Comment by ohbyeongmin** [comment]
Thank you for your report!
I agree with you overall. Some of fields must be not modified by user. I missed that point.
I will improve this feature. Thank you!

**Comment by ohbyeongmin** [comment]
#12
