### ISSUE TITLE
Connect wallet button raises application error on page 404

### ISSUE THREAD

**Issue by mandoopapa** [tokamak-network/tokamak-rollup-hub#9]
### To Reproduce

This is likely due to the fact that this is a testing phase.

Other cases, metamask(wallet) connects without issue, but on the 404 page, clicking connect wallet doesn't work.

![image](https://github.com/user-attachments/assets/c722e5bc-ee73-4d69-9c42-82f8aa33eafe)

Clicking on Tokamak OP or Tokamak ZK+, for example, will call the 404 page.

![image](https://github.com/user-attachments/assets/2262cc3b-791e-489f-a555-b75d5bf654fb)

From there, click Connect wallet and you'll see the screen above.

### Current vs. Expected behavior

I think we could just make GNB disappear altogether when the 404 page pops up, or at least make the Connect Wallet button invisible.

### What browsers are you seeing the problem on?

Chrome

**Comment by ohbyeongmin** [comment]
Thank you for your report!
I will fix it.
